# Generated by Django 5.2.4 on 2025-08-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_auto_20250803_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='conceptofday',
            name='concept_type',
        ),
        migrations.RemoveField(
            model_name='conceptofday',
            name='date',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=256),
        ),
        migrations.AddField(
            model_name='problem',
            name='time_limit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='submission',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory_used',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='test_cases_passed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_test_cases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('MLE', 'Memory Limit Exceeded'), ('PE', 'Presentation Error')], default='WA', max_length=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='auth_app.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('WA', 'Wrong Answer'), ('TLE', 'Time Limit Exceeded'), ('RE', 'Runtime Error'), ('CE', 'Compilation Error'), ('MLE', 'Memory Limit Exceeded'), ('PE', 'Presentation Error')], max_length=10)),
                ('execution_time', models.FloatField(blank=True, null=True)),
                ('memory_used', models.IntegerField(blank=True, null=True)),
                ('actual_output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='auth_app.submission')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth_app.testcase')),
            ],
        ),
    ]
